apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ingress-nginx
  name: AppConf
data:
  MYSQL_DATABASE_USER: "root"
  MYSQL_DATABASE_PASSWORD: "root"
  MYSQL_DATABASE_DB: "BucketList"
  MYSQL_DATABASE_HOST: "db-service"
